export * from './gold_standard_allergy.api'
export * from './gold_standard_generic_product_clinical.api'
export * from './gold_standard_generic_product.api'
export * from './gold_standard_specific_drug_product.api'
export * from './gold_standard_specific_product.api'
export * from './gold_standard_therapeutic_concept.api'
